# Generated by Django 3.0.3 on 2020-05-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200513_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreviewreply',
            name='reply',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='state',
            field=models.CharField(choices=[('Block', 'Block'), ('Wait', 'Wait'), ('Accept', 'Accept'), ('New_Accept', 'New_Accept')], default='Wait', max_length=35),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='reply',
            field=models.TextField(blank=True),
        ),
    ]
