# Generated by Django 3.0.3 on 2020-05-08 18:02

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_image',
            field=models.ImageField(default=None, max_length=255, storage=django.core.files.storage.FileSystemStorage(location='/mnt/1b0e4df8-44c6-432c-8b18-860457404e7e/home/s4/Sources/jgreen44/media/uploads'), upload_to='', verbose_name='Verification Image'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='state',
            field=models.CharField(choices=[('New_Accept', 'New_Accept'), ('Accept', 'Accept'), ('Wait', 'Wait'), ('Block', 'Block')], default='Wait', max_length=35),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', max_length=255, storage=django.core.files.storage.FileSystemStorage(location='/mnt/1b0e4df8-44c6-432c-8b18-860457404e7e/home/s4/Sources/jgreen44/media/uploads'), upload_to='', verbose_name='Profile Image'),
        ),
    ]
