# Generated by Django 3.0.3 on 2020-05-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='state',
            field=models.CharField(choices=[('New_Accept', 'New_Accept'), ('Accept', 'Accept'), ('Block', 'Block'), ('Wait', 'Wait')], default='Wait', max_length=35),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Single Male', 'Male'), ('Single Female', 'Female'), ('Couple', 'Couple')], default='Single Male', max_length=13),
        ),
    ]
