# Generated by Django 3.0.3 on 2020-04-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('recipient_id', models.IntegerField()),
                ('state', models.CharField(choices=[('Wait', 'Wait'), ('Reject', 'Reject'), ('Accept', 'Accept')], default='Wait', max_length=35)),
            ],
        ),
    ]
