# Generated by Django 3.0.3 on 2020-05-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='state',
            field=models.CharField(choices=[('Wait', 'Wait'), ('Accept', 'Accept'), ('New_Accept', 'New_Accept'), ('Block', 'Block')], default='Wait', max_length=35),
        ),
    ]
