# Generated by Django 3.0.3 on 2020-05-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200513_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreview',
            options={'get_latest_by': 'created_at', 'verbose_name': 'User Review', 'verbose_name_plural': 'User Reviews'},
        ),
        migrations.AlterField(
            model_name='friend',
            name='state',
            field=models.CharField(choices=[('Accept', 'Accept'), ('New_Accept', 'New_Accept'), ('Block', 'Block'), ('Wait', 'Wait')], default='Wait', max_length=35),
        ),
        migrations.AlterModelTable(
            name='userreview',
            table='user_review',
        ),
    ]
