# Generated by Django 3.0.3 on 2020-05-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200508_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='state',
            field=models.CharField(choices=[('Block', 'Block'), ('New_Accept', 'New_Accept'), ('Accept', 'Accept'), ('Wait', 'Wait')], default='Wait', max_length=35),
        ),
    ]
