# Generated by Django 3.0.3 on 2020-04-16 08:16

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='sender_firstName',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='friend',
            name='sender_image',
            field=models.ImageField(default='default.jpg', upload_to=users.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='friend',
            name='sender_lastName',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='friend',
            name='state',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Wait', 'Wait')], default='Wait', max_length=35),
        ),
    ]
