# Generated by Django 3.0.3 on 2020-05-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200508_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approved',
        ),
        migrations.AddField(
            model_name='profile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friend',
            name='state',
            field=models.CharField(choices=[('New_Accept', 'New_Accept'), ('Wait', 'Wait'), ('Block', 'Block'), ('Accept', 'Accept')], default='Wait', max_length=35),
        ),
    ]
