# Generated by Django 3.0.3 on 2020-04-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200416_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='state',
            field=models.CharField(choices=[('Wait', 'Wait'), ('Accept', 'Accept'), ('Block', 'Block')], default='Wait', max_length=35),
        ),
    ]
