# Generated by Django 3.0.3 on 2020-05-13 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200513_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='post',
            new_name='content',
        ),
        migrations.AddField(
            model_name='userreview',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='friend',
            name='state',
            field=models.CharField(choices=[('Wait', 'Wait'), ('Block', 'Block'), ('Accept', 'Accept'), ('New_Accept', 'New_Accept')], default='Wait', max_length=35),
        ),
        migrations.CreateModel(
            name='UserReviewReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserReview')),
            ],
            options={
                'verbose_name': 'User Review Reply',
                'verbose_name_plural': 'User Review Replies',
                'db_table': 'user_review_reply',
                'get_latest_by': 'created_at',
            },
        ),
    ]
