# Generated by Django 3.0.3 on 2020-04-16 16:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200416_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='recipient_firstName',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='friend',
            name='recipient_image',
            field=models.ImageField(default='default.jpg', upload_to=users.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='friend',
            name='recipient_lastName',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='friend',
            name='state',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Wait', 'Wait'), ('Block', 'Block')], default='Wait', max_length=35),
        ),
    ]
