# Generated by Django 3.0.3 on 2020-05-14 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='conversation',
            new_name='convo',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='last_message_id',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='last_update',
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.Message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friend',
            name='state',
            field=models.CharField(choices=[('Wait', 'Wait'), ('New_Accept', 'New_Accept'), ('Block', 'Block'), ('Accept', 'Accept')], default='Wait', max_length=35),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ProfileAddress'),
        ),
    ]
