# Generated by Django 3.0.3 on 2020-05-14 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200513_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Message'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='state',
            field=models.CharField(choices=[('New_Accept', 'New_Accept'), ('Block', 'Block'), ('Wait', 'Wait'), ('Accept', 'Accept')], default='Wait', max_length=35),
        ),
    ]
