# Generated by Django 3.0.3 on 2020-05-13 22:40

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200513_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='state',
            field=models.CharField(choices=[('New_Accept', 'New_Accept'), ('Accept', 'Accept'), ('Block', 'Block'), ('Wait', 'Wait')], default='Wait', max_length=35),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='C:\\Users\\trevo\\PycharmProjects\\jason-site\\app\\media\\uploads'), upload_to='', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_image',
            field=models.ImageField(blank=True, default='default.jpg', max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='C:\\Users\\trevo\\PycharmProjects\\jason-site\\app\\media\\uploads'), upload_to='', verbose_name='Verification Image'),
        ),
    ]
