version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: django
      POSTGRES_DB: django
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"