# Generated by Django 3.0.3 on 2020-05-17 21:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=1589750208)),
                ('last_timestamp', models.IntegerField(default=1589750208)),
                ('content', models.TextField()),
                ('image', models.CharField(blank=True, max_length=250)),
                ('upvote_count', models.IntegerField(default=0)),
                ('downvote_count', models.IntegerField(default=0)),
            ],
            options={
                'get_latest_by': 'last_timestamp',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=1589750208)),
                ('last_timestamp', models.IntegerField(default=1589750208)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), default=list, null=True, size=None)),
                ('state', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=35)),
                ('like_count', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('dislike_count', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
            ],
            options={
                'get_latest_by': 'last_timestamp',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=1589750208)),
                ('last_timestamp', models.IntegerField(default=1589750208)),
                ('value', models.SmallIntegerField()),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
            options={
                'get_latest_by': 'last_timestamp',
                'abstract': False,
            },
        ),
    ]
